// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCmG1_LczrjsUUSJ_Y0pa0C268w5GHE0u8",
      authDomain: "carb-49c8c.firebaseapp.com",
      projectId: "carb-49c8c",
      storageBucket: "carb-49c8c.appspot.com",
      messagingSenderId: "1759831562",
      appId: "1:1759831562:web:0e30a8cd80ad1449f021f3",
      measurementId: "G-7VF6X903F6"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCmG1_LczrjsUUSJ_Y0pa0C268w5GHE0u8",
    appId: "1:1759831562:android:558ffafa79ab70a8f021f3",
    messagingSenderId: 'Place your key',
    projectId: 'com.carbmobile',
    storageBucket: 'carb-49c8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Place your key',
    appId: '1:1759831562:ios:8fea3bfb5e0b85a2f021f3',
    messagingSenderId: 'Place your key',
    projectId: 'Place your key',
    storageBucket: 'Place your key',
    androidClientId: 'Place your key',
    iosClientId: 'Place your key',
    iosBundleId: 'Place your key',
  );
}
